# Generated by Django 3.0.6 on 2020-07-02 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20200702_0754'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluemcerStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_city', models.CharField(max_length=200)),
                ('audience_gender_age', models.CharField(max_length=200)),
                ('impressions_10_days', models.TextField()),
                ('impressions_30_days', models.TextField()),
                ('impressions_6_months', models.TextField()),
                ('impressions_1_year', models.TextField()),
                ('follower_count_10_days', models.TextField()),
                ('follower_count_30_days', models.TextField()),
                ('follower_count_6_months', models.TextField()),
                ('follower_count_1_year', models.TextField()),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Influencer')),
            ],
            options={
                'verbose_name_plural': 'Influencer Statistics',
            },
        ),
        migrations.CreateModel(
            name='EndorsingPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.TextField()),
                ('media_embed_url', models.URLField(max_length=1000)),
                ('media_type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('CAROUSEL_ALBUM', 'CAROUSEL_ALBUM')], max_length=20)),
                ('engagement', models.TextField()),
                ('impressions', models.TextField()),
                ('reach', models.TextField()),
                ('saved', models.TextField()),
                ('video_views', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.Campaign')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Influencer')),
            ],
        ),
    ]
