# Generated by Django 3.0.6 on 2020-07-05 18:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_city', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=2), size=None)),
                ('audience_gender_age', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=2), size=None)),
                ('impressions', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=2), size=None)),
                ('follower_counts', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=2), size=None)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Influencer')),
            ],
            options={
                'verbose_name_plural': 'Influencer Statistics',
            },
        ),
        migrations.CreateModel(
            name='EndorsingPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.TextField()),
                ('media_embed_url', models.URLField(max_length=1000)),
                ('media_type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('CAROUSEL_ALBUM', 'CAROUSEL_ALBUM')], max_length=20)),
                ('engagement', models.TextField()),
                ('impressions', models.TextField()),
                ('reach', models.TextField()),
                ('saved', models.TextField()),
                ('video_views', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.Campaign')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Influencer')),
            ],
        ),
    ]
