# Generated by Django 3.0.6 on 2020-07-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0002_auto_20200702_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencerstatistics',
            old_name='follower_count_10_days',
            new_name='follower_counts',
        ),
        migrations.RenameField(
            model_name='influencerstatistics',
            old_name='follower_count_1_year',
            new_name='impressions',
        ),
        migrations.RemoveField(
            model_name='influencerstatistics',
            name='follower_count_30_days',
        ),
        migrations.RemoveField(
            model_name='influencerstatistics',
            name='follower_count_6_months',
        ),
        migrations.RemoveField(
            model_name='influencerstatistics',
            name='impressions_10_days',
        ),
        migrations.RemoveField(
            model_name='influencerstatistics',
            name='impressions_1_year',
        ),
        migrations.RemoveField(
            model_name='influencerstatistics',
            name='impressions_30_days',
        ),
        migrations.RemoveField(
            model_name='influencerstatistics',
            name='impressions_6_months',
        ),
    ]
