# Generated by Django 3.0.6 on 2020-07-21 16:47

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_brand', models.BooleanField(default=False)),
                ('is_account_activated', models.BooleanField(default=True)),
                ('is_google_account', models.BooleanField(default=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.get_profile_picture_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('website', models.URLField(blank=True, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('is_subscription_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_unlocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_read_engagement', models.BooleanField(default=False)),
                ('instagram_basic', models.BooleanField(default=False)),
                ('instagram_manage_insights', models.BooleanField(default=False)),
                ('pages_show_list', models.BooleanField(default=False)),
                ('user_token', models.TextField()),
                ('user_id', models.TextField()),
                ('fb_page_id', models.TextField()),
                ('ig_page_id', models.TextField()),
                ('ig_username', models.CharField(blank=True, max_length=200)),
                ('ig_follower_count', models.CharField(blank=True, max_length=200)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Influencer')),
            ],
            options={
                'verbose_name_plural': 'Facebook Permissions',
            },
        ),
    ]
