# Generated by Django 3.0.6 on 2020-05-29 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FacebookPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_show_list', models.BooleanField(default=False)),
                ('instagram_basic', models.BooleanField(default=False)),
                ('instagram_manage_insights', models.BooleanField(default=False)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Influencer')),
            ],
        ),
    ]
