# Generated by Django 3.0.6 on 2020-06-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpermissions',
            name='ig_follower_count',
            field=models.CharField(default='alphonso_mangoes_me', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebookpermissions',
            name='ig_username',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facebookpermissions',
            name='fb_page_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='facebookpermissions',
            name='ig_page_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='facebookpermissions',
            name='user_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='facebookpermissions',
            name='user_token',
            field=models.TextField(),
        ),
    ]
