# Generated by Django 3.0.6 on 2020-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpermissions',
            name='user_token',
            field=models.TextField(default=''),
        ),
    ]
