# Generated by Django 3.0.6 on 2020-12-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200906_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_test_account',
            field=models.BooleanField(default=False),
        ),
    ]
