# Generated by Django 3.0.6 on 2020-05-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_facebookpermissions_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpermissions',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
