# Generated by Django 3.0.6 on 2020-06-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200630_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpermissions',
            name='ig_follower_count',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='facebookpermissions',
            name='ig_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
