# Generated by Django 3.0.6 on 2020-05-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200529_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookpermissions',
            options={'verbose_name_plural': 'Facebook Permissions'},
        ),
    ]
