# Generated by Django 3.0.6 on 2020-05-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200529_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookpermissions',
            old_name='pages_show_list',
            new_name='pages_read_engagement',
        ),
    ]
