# Generated by Django 3.0.6 on 2020-07-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200630_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencer',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
