# Generated by Django 3.0.6 on 2020-05-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_facebookpermissions_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpermissions',
            name='user_id',
            field=models.TextField(default=''),
        ),
    ]
