# Generated by Django 3.0.6 on 2020-05-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200531_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpermissions',
            name='fb_page_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='facebookpermissions',
            name='ig_page_id',
            field=models.TextField(default=''),
        ),
    ]
