# Generated by Django 3.0.6 on 2020-06-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200531_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_account_activated',
            field=models.BooleanField(default=True),
        ),
    ]
