# Generated by Django 3.0.6 on 2020-06-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_account_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpermissions',
            name='pages_show_list',
            field=models.BooleanField(default=False),
        ),
    ]
